# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Poetry testt

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Using Cached Poetry
      id: cache-poetry
      uses: actions/cache@v3
      with:
        key: poetry-cache-0
        path: |
          ~/.local/share/pypoetry
          ~/.local/bin/poetry
          ~/.config/pypoetry
    - name: Install Poetry
      if: ${{steps.cache-poetry.outputs.cache-hit}} != 'true'
      run: |
        pipx install poetry
        # poetry config virtualenvs.in-project false
          
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - run: poetry install
    - run: poetry run selenium  
